import 'package:flutter/material.dart';
import '../../core/localization/app_localizations.dart';
import '../../models/user_role.dart';
import '../../widgets/app_components.dart';
import '../../widgets/biometric_background.dart';
import '../dashboard/dashboard_view.dart';
class RegisterView extends StatefulWidget { const RegisterView({super.key,required this.language,required this.themeMode,required this.onLanguageChanged,required this.onThemeModeChanged}); final AppLanguage language; final ThemeMode themeMode; final ValueChanged<AppLanguage> onLanguageChanged; final ValueChanged<ThemeMode> onThemeModeChanged; @override State<RegisterView> createState()=>_RegisterViewState(); }
class _RegisterViewState extends State<RegisterView>{UserRole _role=UserRole.athlete; @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(leading:const BackButton()),body:BiometricBackground(variant:1,child:ListView(padding:const EdgeInsets.all(24),children:[Text(context.tr('createAccount'),style:Theme.of(context).textTheme.headlineMedium?.copyWith(fontWeight:FontWeight.w800)),Text(context.tr('roleHint')),const SizedBox(height:20),Row(children:[Expanded(child:_RoleChoice(label:context.tr('athlete'),icon:Icons.directions_run,selected:_role==UserRole.athlete,onPressed:()=>setState(()=>_role=UserRole.athlete))),const SizedBox(width:12),Expanded(child:_RoleChoice(label:context.tr('coach'),icon:Icons.sports,selected:_role==UserRole.coach,onPressed:()=>setState(()=>_role=UserRole.coach)))]),const SizedBox(height:18),AppCard(child:Column(children:[AppTextField(label:context.tr('fullName'),icon:Icons.badge_outlined),const SizedBox(height:12),AppTextField(label:context.tr('organization'),icon:Icons.groups_outlined),const SizedBox(height:12),AppTextField(label:context.tr('email'),icon:Icons.mail_outline),const SizedBox(height:12),AppTextField(label:context.tr('password'),icon:Icons.lock_outline,obscureText:true),const SizedBox(height:12),AppTextField(label:context.tr('confirmPassword'),icon:Icons.lock_reset_outlined,obscureText:true)])),const SizedBox(height:18),PrimaryButton(label:context.tr('createAccount'),icon:Icons.person_add,onPressed:()=>Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>DashboardView(role:_role,language:widget.language,themeMode:widget.themeMode,onLanguageChanged:widget.onLanguageChanged,onThemeModeChanged:widget.onThemeModeChanged)),(route)=>false))])));}
class _RoleChoice extends StatelessWidget { const _RoleChoice({required this.label,required this.icon,required this.selected,required this.onPressed}); final String label; final IconData icon; final bool selected; final VoidCallback onPressed; @override Widget build(BuildContext context)=>InkWell(onTap:onPressed,borderRadius:BorderRadius.circular(16),child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(borderRadius:BorderRadius.circular(16),border:Border.all(color:selected?Theme.of(context).colorScheme.primary:Theme.of(context).colorScheme.outlineVariant),color:selected?Theme.of(context).colorScheme.primary.withValues(alpha:.12):null),child:Column(children:[Icon(icon),const SizedBox(height:8),Text(label)]))); }
